[phases.setup]
nixPkgs = ['python311', 'python311Packages.pip']
aptPkgs = ['python3-pip', 'python3-venv']

[phases.install]
cmds = [
    'python -m pip install --upgrade pip',
    'pip install -r requirements.txt'
]

[start]
cmd = 'uvicorn app.main:app --host 0.0.0.0 --port ${PORT:-8000}'

[deploy]
startCommand = 'uvicorn app.main:app --host 0.0.0.0 --port ${PORT:-8000}'
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10 